In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import polars as pl
from utils import cleaning

In [2]:
# Set to True for initialize the dataset

if False:
    cleaning.init()

In [3]:
cfg = pl.Config()
cfg.set_tbl_rows(1000)

polars.config.Config

In [6]:
year = 2021
lf1 = cleaning.clean_dataset(year)
lf1.describe()

shape: (9, 34)
┌────────────┬──────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ statistic  ┆ DIABETES ┆ SEX      ┆ INCOME   ┆ … ┆ STROKE   ┆ ASTHMA   ┆ SMOKER   ┆ EXERCISE │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str        ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞════════════╪══════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ count      ┆ 433900.0 ┆ 433900.0 ┆ 340734.0 ┆ … ┆ 432783.0 ┆ 430691.0 ┆ 409349.0 ┆ 433076.0 │
│ null_count ┆ 0.0      ┆ 0.0      ┆ 93166.0  ┆ … ┆ 1117.0   ┆ 3209.0   ┆ 24551.0  ┆ 824.0    │
│ mean       ┆ 2.75734  ┆ 1.531487 ┆ 4.031664 ┆ … ┆ 1.960534 ┆ 2.765549 ┆ 3.371998 ┆ 1.244308 │
│ std        ┆ 0.703687 ┆ 0.499008 ┆ 1.300427 ┆ … ┆ 0.1947   ┆ 0.612303 ┆ 0.932287 ┆ 0.429677 │
│ min        ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ 1.0      │
│ 25%        ┆ 3.0      ┆ 1.0      ┆ 3.0      ┆ … ┆ 2.0      ┆ 3.0      ┆ 3.0      ┆ 1.0      │
│ 50%        ┆ 3.0      ┆ 2.0      ┆ 5.0      ┆ … ┆ 2.0      ┆ 3.0      ┆ 4.0      ┆ 1.0      │
│ 75%        ┆ 3.0      ┆ 2.0      ┆ 5.0      ┆ … ┆ 2.0      ┆ 3.0      ┆ 4.0      ┆ 1.0      │
│ max        ┆ 4.0      ┆ 2.0      ┆ 5.0      ┆ … ┆ 2.0      ┆ 3.0      ┆ 4.0      ┆ 2.0      │
└────────────┴──────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [7]:
lf2023 = cleaning.clean_dataset(2023)
lf2021 = cleaning.clean_dataset(2021)
lf2019 = cleaning.clean_dataset(2019)
lf2017 = cleaning.clean_dataset(2017)

In [8]:
lf_full = pl.concat([lf2023, lf2021, lf2019, lf2017])

In [9]:
lf_full.describe()

shape: (9, 34)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ DIABETES  ┆ SEX       ┆ INCOME    ┆ … ┆ STROKE    ┆ ASTHMA    ┆ SMOKER    ┆ EXERCISE │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1.722563e ┆ 1.722287e ┆ 1.390882e ┆ … ┆ 1.717926e ┆ 1.709952e ┆ 1.638215e ┆ 1.665077 │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0.0       ┆ 276.0     ┆ 331681.0  ┆ … ┆ 4637.0    ┆ 12611.0   ┆ 84348.0   ┆ 57486.0  │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 2.748881  ┆ 1.538847  ┆ 3.93255   ┆ … ┆ 1.957696  ┆ 2.764743  ┆ 3.363602  ┆ 1.25932  │
│ std       ┆ 0.710784  ┆ 0.498489  ┆ 1.370112  ┆ … ┆ 0.201283  ┆ 0.611112  ┆ 0.9331    ┆ 0.438262 │
│ min       ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ 25%       ┆ 3.0       ┆ 1.0       ┆ 3.0       ┆ … ┆ 2.0       ┆ 3.0       ┆ 3.0       ┆ 1.0      │
│ 50%       ┆ 3.0       ┆ 2.0       ┆ 5.0       ┆ … ┆ 2.0       ┆ 3.0       ┆ 4.0       ┆ 1.0      │
│ 75%       ┆ 3.0       ┆ 2.0       ┆ 5.0       ┆ … ┆ 2.0       ┆ 3.0       ┆ 4.0       ┆ 2.0      │
│ max       ┆ 4.0       ┆ 2.0       ┆ 5.0       ┆ … ┆ 2.0       ┆ 3.0       ┆ 4.0       ┆ 2.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
lf_full.sink_parquet("../datasets/BRFSS/out.parquet")