In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import polars as pl
from utils.cleaning import *

In [2]:
# Set to True for initialize the dataset

if False:
    init()

In [3]:
cfg = pl.Config()
cfg.set_tbl_rows(1000)

polars.config.Config

In [4]:
# brfss_dataset_path = "../datasets/BRFSS/"
# brfss_path = brfss_dataset_path + "2023.parquet"

# lf = pl.scan_parquet(
#     brfss_path,
#     missing_columns='insert'
# )

In [5]:
year = 2021
lf1 = clean_dataset(year)
lf1.describe()

shape: (9, 34)
┌────────────┬──────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬───────────────┐
│ statistic  ┆ DIABETES ┆ SEX      ┆ INCOME   ┆ … ┆ SMOKER   ┆ EXERCISE ┆ VETERAN  ┆ CANCER_DIAGNO │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ SIS           │
│ str        ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ ---           │
│            ┆          ┆          ┆          ┆   ┆          ┆          ┆          ┆ f64           │
╞════════════╪══════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪═══════════════╡
│ count      ┆ 437708.0 ┆ 437708.0 ┆ 343849.0 ┆ … ┆ 412968.0 ┆ 436880.0 ┆ 434645.0 ┆ 435979.0      │
│ null_count ┆ 0.0      ┆ 0.0      ┆ 93859.0  ┆ … ┆ 24740.0  ┆ 828.0    ┆ 3063.0   ┆ 1729.0        │
│ mean       ┆ 0.140331 ┆ 0.53554  ┆ 3.031336 ┆ … ┆ 2.372017 ┆ 0.244271 ┆ 0.879396 ┆ 0.169001      │
│ std        ┆ 0.347331 ┆ 0.498736 ┆ 1.300743 ┆ … ┆ 0.932715 ┆ 0.429654 ┆ 0.325667 ┆ 0.374753      │
│ min        ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0           │
│ 25%        ┆ 0.0      ┆ 0.0      ┆ 2.0      ┆ … ┆ 2.0      ┆ 0.0      ┆ 1.0      ┆ 0.0           │
│ 50%        ┆ 0.0      ┆ 1.0      ┆ 4.0      ┆ … ┆ 3.0      ┆ 0.0      ┆ 1.0      ┆ 0.0           │
│ 75%        ┆ 0.0      ┆ 1.0      ┆ 4.0      ┆ … ┆ 3.0      ┆ 0.0      ┆ 1.0      ┆ 0.0           │
│ max        ┆ 1.0      ┆ 1.0      ┆ 4.0      ┆ … ┆ 3.0      ┆ 1.0      ┆ 1.0      ┆ 1.0           │
└────────────┴──────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴───────────────┘

In [6]:
lf2023 = clean_dataset(2023)
lf2021 = clean_dataset(2021)
lf2019 = clean_dataset(2019)
lf2017 = clean_dataset(2017)

In [7]:
lf_full = pl.concat([lf2023, lf2021, lf2019, lf2017])

In [8]:
lf_full.describe()

shape: (9, 34)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ DIABETES  ┆ SEX       ┆ INCOME    ┆ … ┆ SMOKER    ┆ EXERCISE  ┆ VETERAN   ┆ CANCER_D │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ IAGNOSIS │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1.736689e ┆ 1.736413e ┆ 1.402577e ┆ … ┆ 1.651675e ┆ 1.678732e ┆ 1.728167e ┆ 1.728612 │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0.0       ┆ 276.0     ┆ 334112.0  ┆ … ┆ 85014.0   ┆ 57957.0   ┆ 8522.0    ┆ 8077.0   │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 0.143589  ┆ 0.542578  ┆ 2.932089  ┆ … ┆ 2.363691  ┆ 0.259281  ┆ 0.876029  ┆ 0.172811 │
│ std       ┆ 0.350672  ┆ 0.498184  ┆ 1.370426  ┆ … ┆ 0.933513  ┆ 0.43824   ┆ 0.329548  ┆ 0.378084 │
│ min       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 25%       ┆ 0.0       ┆ 0.0       ┆ 2.0       ┆ … ┆ 2.0       ┆ 0.0       ┆ 1.0       ┆ 0.0      │
│ 50%       ┆ 0.0       ┆ 1.0       ┆ 4.0       ┆ … ┆ 3.0       ┆ 0.0       ┆ 1.0       ┆ 0.0      │
│ 75%       ┆ 0.0       ┆ 1.0       ┆ 4.0       ┆ … ┆ 3.0       ┆ 1.0       ┆ 1.0       ┆ 0.0      │
│ max       ┆ 1.0       ┆ 1.0       ┆ 4.0       ┆ … ┆ 3.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
lf_full.sink_parquet("../datasets/BRFSS/out_v3.parquet")

In [10]:
df = pl.read_parquet("../datasets/BRFSS/out_v3.parquet")

In [11]:
df.head(7)

shape: (7, 33)
┌──────────┬─────┬────────┬───────────┬───┬────────┬──────────┬─────────┬──────────────────┐
│ DIABETES ┆ SEX ┆ INCOME ┆ ARTHRITIS ┆ … ┆ SMOKER ┆ EXERCISE ┆ VETERAN ┆ CANCER_DIAGNOSIS │
│ ---      ┆ --- ┆ ---    ┆ ---       ┆   ┆ ---    ┆ ---      ┆ ---     ┆ ---              │
│ u8       ┆ u8  ┆ u8     ┆ u8        ┆   ┆ u8     ┆ u8       ┆ u8      ┆ i32              │
╞══════════╪═════╪════════╪═══════════╪═══╪════════╪══════════╪═════════╪══════════════════╡
│ 1        ┆ 1   ┆ null   ┆ 1         ┆ … ┆ 3      ┆ 1        ┆ 1       ┆ 0                │
│ 0        ┆ 1   ┆ null   ┆ 0         ┆ … ┆ 3      ┆ 0        ┆ 1       ┆ 0                │
│ 0        ┆ 1   ┆ 0      ┆ 0         ┆ … ┆ 2      ┆ 0        ┆ 1       ┆ 0                │
│ 0        ┆ 1   ┆ null   ┆ 0         ┆ … ┆ 3      ┆ 0        ┆ 1       ┆ 1                │
│ 1        ┆ 1   ┆ 4      ┆ 0         ┆ … ┆ 3      ┆ 0        ┆ 1       ┆ 1                │
│ 0        ┆ 1   ┆ 4      ┆ 1         ┆ … ┆ 3      ┆ 0        ┆ 0       ┆ 0                │
│ 0        ┆ 0   ┆ 3      ┆ 0         ┆ … ┆ 2      ┆ 1        ┆ 0       ┆ 0                │
└──────────┴─────┴────────┴───────────┴───┴────────┴──────────┴─────────┴──────────────────┘

In [12]:
df.shape

(1736689, 33)