In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import polars as pl
from utils.cleaning import *

In [2]:
# Set to True for initialize the dataset

if False:
    init()

In [3]:
cfg = pl.Config()
cfg.set_tbl_rows(1000)

polars.config.Config

In [4]:
brfss_dataset_path = "../datasets/BRFSS/"
brfss_path = brfss_dataset_path + "2023.parquet"

lf = pl.scan_parquet(
    brfss_path,
    missing_columns='insert'
)

In [5]:
year = 2021
lf1 = clean_dataset(year)
lf1.describe()

shape: (9, 21)
┌────────────┬──────────┬──────────┬──────────┬───┬──────────┬──────────┬─────────────┬────────────┐
│ statistic  ┆ DIABETES ┆ SEX      ┆ INCOME   ┆ … ┆ SMOKER   ┆ EXERCISE ┆ TOTAL_COMOR ┆ TOTAL_DISA │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ BIDITY      ┆ BILITY     │
│ str        ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ ---         ┆ ---        │
│            ┆          ┆          ┆          ┆   ┆          ┆          ┆ f64         ┆ f64        │
╞════════════╪══════════╪══════════╪══════════╪═══╪══════════╪══════════╪═════════════╪════════════╡
│ count      ┆ 433900.0 ┆ 433900.0 ┆ 340734.0 ┆ … ┆ 409349.0 ┆ 433076.0 ┆ 433900.0    ┆ 433900.0   │
│ null_count ┆ 0.0      ┆ 0.0      ┆ 93166.0  ┆ … ┆ 24551.0  ┆ 824.0    ┆ 0.0         ┆ 0.0        │
│ mean       ┆ 0.132786 ┆ 1.531487 ┆ 4.031664 ┆ … ┆ 3.371998 ┆ 1.244308 ┆ 1.044844    ┆ 0.504243   │
│ std        ┆ 0.339344 ┆ 0.499008 ┆ 1.300427 ┆ … ┆ 0.932287 ┆ 0.429677 ┆ 1.210908    ┆ 0.970691   │
│ min        ┆ 0.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 1.0      ┆ 1.0      ┆ 0.0         ┆ 0.0        │
│ 25%        ┆ 0.0      ┆ 1.0      ┆ 3.0      ┆ … ┆ 3.0      ┆ 1.0      ┆ 0.0         ┆ 0.0        │
│ 50%        ┆ 0.0      ┆ 2.0      ┆ 5.0      ┆ … ┆ 4.0      ┆ 1.0      ┆ 1.0         ┆ 0.0        │
│ 75%        ┆ 0.0      ┆ 2.0      ┆ 5.0      ┆ … ┆ 4.0      ┆ 1.0      ┆ 2.0         ┆ 1.0        │
│ max        ┆ 1.0      ┆ 2.0      ┆ 5.0      ┆ … ┆ 4.0      ┆ 2.0      ┆ 9.0         ┆ 6.0        │
└────────────┴──────────┴──────────┴──────────┴───┴──────────┴──────────┴─────────────┴────────────┘

In [6]:
lf2023 = clean_dataset(2023)
lf2021 = clean_dataset(2021)
lf2019 = clean_dataset(2019)
lf2017 = clean_dataset(2017)

In [7]:
lf_full = pl.concat([lf2023, lf2021, lf2019, lf2017])

In [8]:
lf_full.describe()

shape: (9, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ DIABETES  ┆ SEX       ┆ INCOME    ┆ … ┆ SMOKER    ┆ EXERCISE  ┆ TOTAL_COM ┆ TOTAL_DI │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ORBIDITY  ┆ SABILITY │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1.722563e ┆ 1.722287e ┆ 1.390882e ┆ … ┆ 1.638215e ┆ 1.665077e ┆ 1.722563e ┆ 1.722563 │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0.0       ┆ 276.0     ┆ 331681.0  ┆ … ┆ 84348.0   ┆ 57486.0   ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 0.136566  ┆ 1.538847  ┆ 3.93255   ┆ … ┆ 3.363602  ┆ 1.25932   ┆ 1.067932  ┆ 0.523397 │
│ std       ┆ 0.343388  ┆ 0.498489  ┆ 1.370112  ┆ … ┆ 0.9331    ┆ 0.438262  ┆ 1.233493  ┆ 0.992781 │
│ min       ┆ 0.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 0.0       ┆ 0.0      │
│ 25%       ┆ 0.0       ┆ 1.0       ┆ 3.0       ┆ … ┆ 3.0       ┆ 1.0       ┆ 0.0       ┆ 0.0      │
│ 50%       ┆ 0.0       ┆ 2.0       ┆ 5.0       ┆ … ┆ 4.0       ┆ 1.0       ┆ 1.0       ┆ 0.0      │
│ 75%       ┆ 0.0       ┆ 2.0       ┆ 5.0       ┆ … ┆ 4.0       ┆ 2.0       ┆ 2.0       ┆ 1.0      │
│ max       ┆ 1.0       ┆ 2.0       ┆ 5.0       ┆ … ┆ 4.0       ┆ 2.0       ┆ 9.0       ┆ 6.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
lf_full.sink_parquet("../datasets/BRFSS/out.parquet")

In [10]:
df = pl.read_parquet("../datasets/BRFSS/out.parquet")

In [11]:
df.head(5)

shape: (5, 20)
┌──────────┬─────┬────────┬────────┬───┬────────┬──────────┬───────────────────┬──────────────────┐
│ DIABETES ┆ SEX ┆ INCOME ┆ HIGHBP ┆ … ┆ SMOKER ┆ EXERCISE ┆ TOTAL_COMORBIDITY ┆ TOTAL_DISABILITY │
│ ---      ┆ --- ┆ ---    ┆ ---    ┆   ┆ ---    ┆ ---      ┆ ---               ┆ ---              │
│ u8       ┆ u8  ┆ u8     ┆ u8     ┆   ┆ u8     ┆ u8       ┆ u8                ┆ u8               │
╞══════════╪═════╪════════╪════════╪═══╪════════╪══════════╪═══════════════════╪══════════════════╡
│ 1        ┆ 2   ┆ null   ┆ 2      ┆ … ┆ 4      ┆ 2        ┆ 0                 ┆ 1                │
│ 0        ┆ 2   ┆ null   ┆ 2      ┆ … ┆ 4      ┆ 1        ┆ 2                 ┆ 1                │
│ 0        ┆ 2   ┆ 1      ┆ 2      ┆ … ┆ 3      ┆ 1        ┆ 2                 ┆ 3                │
│ 0        ┆ 2   ┆ null   ┆ 1      ┆ … ┆ 4      ┆ 1        ┆ 4                 ┆ 1                │
│ 1        ┆ 2   ┆ 5      ┆ 2      ┆ … ┆ 4      ┆ 1        ┆ 3                 ┆ 3                │
└──────────┴─────┴────────┴────────┴───┴────────┴──────────┴───────────────────┴──────────────────┘

In [12]:
df.shape

(1722563, 20)